services:
  - type: web
    name: smartbiz-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.11
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: smartbiz-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: smartbiz-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: smartbiz-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: smartbiz-db
          property: password
      - key: SECRET_KEY
        value: pK179z2QQzIYt9e4l5C0e7kvdIX6p4y9d7_AQIHTcu_hh35U40ds9uT8eKT5gj5tunErk1byXqUz5O5ysh6cQ
